version: '3.8'

services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/local/backend/Dockerfile
    entrypoint: /app/docker/backend/server-entrypoint.sh
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .envs/.local/django.env
    networks:
      - djinni-clone-api
    depends_on:
      - redis

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/local/backend/Dockerfile
    entrypoint: /app/docker/backend/worker-entrypoint.sh
    volumes:
      - static_volume:/app/backend/staticfiles
    env_file:
      - .envs/.local/django.env
    networks:
      - djinni-clone-api
    depends_on:
      - server
      - redis

  celery-beat:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/local/backend/Dockerfile
    entrypoint: /app/docker/backend/celery-beat-entrypoint.sh
    volumes:
      - static_volume:/app/backend/staticfiles
    env_file:
      - .envs/.local/django.env
    networks:
      - djinni-clone-api
    depends_on:
      - server
      - redis
      - worker

  flower:
    restart: unless-stopped
    image: mher/flower:2.0.0
    command: celery flower --persistent=True --broker=redis://redis:6379/0
    env_file:
      - .envs/.local/django.env
    ports:
      - "5555:555
