# Generated by Django 5.0.3 on 2024-03-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type_profile",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("employer", "Employer")],
                default="employer",
                max_length=20,
                verbose_name="type profile",
            ),
        ),
    ]
