# Generated by Django 5.0.3 on 2024-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_type_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type_profile",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("recruiter", "Recruiter")],
                default="candidate",
                max_length=20,
                verbose_name="type profile",
            ),
        ),
    ]
