# Generated by Django 5.0.3 on 2024-03-23 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_onlinestatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlineUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Online Status",
                "verbose_name_plural": "Online Status",
                "ordering": ["-last_login"],
            },
        ),
        migrations.DeleteModel(
            name="OnlineStatus",
        ),
    ]
