# Generated by Django 5.0.3 on 2024-03-22 11:41

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Company Name")),
                ("bio", models.TextField(verbose_name="Company Bio")),
                ("company_url", models.URLField(blank=True, verbose_name="Company URL")),
                ("dou_url", models.URLField(blank=True, verbose_name="DOU URL")),
                ("country", models.CharField(blank=True, max_length=200, null=True, verbose_name="Country")),
                ("num_employees", models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Number of Employees")),
                ("image", models.ImageField(
                    upload_to=apps.core.services.get_path_upload_image_company,
                    validators=[apps.core.services.validate_image_size],
                    verbose_name="Company Image",
                    db_tablespace="images"
                )),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
