# Generated by Django 5.0.3 on 2024-03-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
    ]
