# Generated by Django 5.0.3 on 2024-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
