# Generated by Django 5.0.3 on 2024-03-20 13:32

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(
                upload_to=apps.core.services.get_path_upload_image_company,
                validators=[apps.core.services.validate_image_size],
            ),
        ),
    ]
