# Generated by Django 5.0.3 on 2024-03-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0003_remove_company_location_company_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="title",
            new_name="name",
        ),
    ]
