# Generated by Django 5.0.3 on 2024-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("other", "0003_alter_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
