# Generated by Django 5.0.3 on 2024-03-20 13:32

import apps.core.services
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="feedback",
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cover_letter", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.services.get_path_upload_cv_file_contact_cv,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            apps.core.services.validate_file_size,
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_vacancy",
                        to="vacancy.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
                "unique_together": {("user", "vacancy")},
            },
        ),
    ]
