# Generated by Django 5.0.3 on 2024-03-20 13:58

import apps.core.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0002_remove_vacancy_feedback_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="cover_letter",
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name="Cover Letter"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="cv_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.core.services.get_path_upload_cv_file_contact_cv,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    apps.core.services.validate_file_size,
                ],
                verbose_name="CV File",
            ),
        ),
    ]
