# Generated by Django 5.0.3 on 2024-03-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_contactcv"),
        ("vacancy", "0003_alter_feedback_cover_letter_alter_feedback_cv_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="cv_file",
        ),
        migrations.AddField(
            model_name="feedback",
            name="contact_cv",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_contact_cv",
                to="accounts.contactcv",
            ),
        ),
    ]
