# Generated by Django 5.0.3 on 2024-03-17 17:16

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("other", "0002_alter_category_options_alter_company_options"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("position", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("image", models.ImageField(upload_to="images/")),
                ("trust_hr", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Recruiter Profile",
                "verbose_name_plural": "Recruiter Profiles",
            },
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("position", models.CharField(blank=True, max_length=50)),
                (
                    "work_exp",
                    models.PositiveIntegerField(
                        blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]
                    ),
                ),
                (
                    "salary_expectation",
                    models.PositiveIntegerField(
                        blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100000)]
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, max_length=50)),
                (
                    "eng_level",
                    models.CharField(
                        choices=[
                            ("NONE", "No English"),
                            ("BEGINNER", "Beginner/Elementary"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("UPPER_INTERMEDIATE", "Upper-Intermediate"),
                            ("ADVANCED", "Advanced/Fluent"),
                        ],
                        default="NONE",
                        max_length=50,
                    ),
                ),
                (
                    "work_exp_bio",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(200),
                            django.core.validators.MaxLengthValidator(1000),
                        ],
                    ),
                ),
                (
                    "employ_options",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("REMOTE", "Remote work"),
                            ("OFFICE", "Office"),
                            ("PART_TIME", "Part-time"),
                            ("FREELANCE", "Freelance (one-off projects)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "find_job",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active search"),
                            ("PASSIVE", "Passive search"),
                            ("DISABLED", "Not looking for a job"),
                        ],
                        default="PASSIVE",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="other.category"),
                ),
                (
                    "skills",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Skills",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Profile",
                "verbose_name_plural": "Candidate Profiles",
            },
        ),
    ]
