# Generated by Django 5.0.3 on 2024-03-25 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_contactcv_phone_number"),
        ("other", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recruiter_profile",
                to="other.company",
            ),
        ),
    ]
