# Generated by Django 5.0.3 on 2024-03-18 14:25

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_candidateprofile_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="country",
            field=django_countries.fields.CountryField(max_length=2, verbose_name="country"),
        ),
    ]
