# Generated by Django 5.0.3 on 2024-03-20 18:25

import apps.core.services
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_candidateprofile_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactCv",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=30, region=None, unique=True, verbose_name="phone number"
                    ),
                ),
                ("telegram_url", models.URLField(blank=True, null=True, verbose_name="telegram url")),
                ("linkedin_url", models.URLField(blank=True, null=True, verbose_name="linkedin url")),
                ("git_hub_url", models.URLField(blank=True, null=True, verbose_name="git hub url")),
                ("portfolio_url", models.URLField(blank=True, null=True, verbose_name="portfolio url")),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.services.get_path_upload_cv_file_contact_cv,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            apps.core.services.validate_file_size,
                        ],
                        verbose_name="CV File",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_cv",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Cv",
                "verbose_name_plural": "Contacts Cv",
            },
        ),
    ]
