# Generated by Django 5.0.3 on 2024-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_candidateprofile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="eng_level",
            field=models.CharField(
                choices=[
                    ("none", "No English"),
                    ("beginner", "Beginner/Elementary"),
                    ("intermediate", "Intermediate"),
                    ("upper_intermediate", "Upper-Intermediate"),
                    ("advanced", "Advanced/Fluent"),
                ],
                default="none",
                max_length=50,
            ),
        ),
    ]
