# Generated by Django 5.0.3 on 2024-03-18 23:23

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_candidateprofile_eng_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="employ_options",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("remote", "Remote work"),
                    ("office", "Office"),
                    ("part_time", "Part-time"),
                    ("freelance", "Freelance (one-off projects)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="find_job",
            field=models.CharField(
                choices=[
                    ("active", "Active search"),
                    ("passive", "Passive search"),
                    ("disabled", "Not looking for a job"),
                ],
                default="passive",
                max_length=50,
            ),
        ),
    ]
