# Generated by Django 5.0.3 on 2024-04-09 15:31

import apps.core.services
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_contactcv_cv_file_alter_contactcv_git_hub_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactcv",
            name="cv_file",
            field=models.FileField(
                blank=True,
                upload_to=apps.core.services.get_path_upload_cv_file_contact_cv,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    apps.core.services.validate_file_size,
                ],
                verbose_name="CV File",
            ),
        ),
        migrations.AlterField(
            model_name="contactcv",
            name="git_hub_url",
            field=models.URLField(blank=True, verbose_name="git hub url"),
        ),
        migrations.AlterField(
            model_name="contactcv",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="linkedin url"),
        ),
        migrations.AlterField(
            model_name="contactcv",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=30, region=None, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="contactcv",
            name="portfolio_url",
            field=models.URLField(blank=True, verbose_name="portfolio url"),
        ),
        migrations.AlterField(
            model_name="contactcv",
            name="telegram_url",
            field=models.URLField(blank=True, verbose_name="telegram url"),
        ),
    ]
