# Generated by Django 5.0.3 on 2024-03-19 22:38

import apps.core.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_candidateprofile_employ_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="image",
            field=models.ImageField(
                upload_to=apps.core.services.get_path_upload_image_candidate,
                validators=[apps.core.services.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="image",
            field=models.ImageField(
                upload_to=apps.core.services.get_path_upload_image_recruiter,
                validators=[apps.core.services.validate_file_size],
            ),
        ),
    ]
