# Generated by Django 5.0.3 on 2024-03-24 14:09

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET_NULL,
                blank=True,
                null=True,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="candidate",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name="candidate_chatrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

