# Generated by Django 5.0.3 on 2024-03-23 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_is_read"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="feedback",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_chatroom",
                to="vacancy.feedback",
            ),
        ),
    ]
