# Generated by Django 5.0.3 on 2024-03-24 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_initial"),
        ("vacancy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="feedback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatroom_feedback",
                to="vacancy.feedback",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruiter_chatrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="chat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chat.chatroom",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together={("recruiter", "candidate", "feedback")},
        ),
    ]

