# Generated by Django 5.0.3 on 2024-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(max_length=1000, verbose_name="Message"),
        ),
    ]
