# Generated by Django 5.0.3 on 2024-03-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatroom_feedback"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="feedback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="feedback_chatroom", to="vacancy.feedback"
            ),
        ),
    ]
