# Generated by Django 5.0.3 on 2024-04-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
        ("vacancy", "0003_alter_offer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="feedback",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_chatroom",
                to="vacancy.feedback",
            ),
        ),
    ]
