# Generated by Django 5.0.3 on 2024-03-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_chatroom_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_bookmark",
            field=models.BooleanField(default=False, verbose_name="Is Bookmark"),
        ),
    ]
