# Generated by Django 5.0.3 on 2024-03-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatroom_is_bookmark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="is_bookmark",
        ),
    ]
